### ISSUE TITLE
Do we host D-man SVG in this repository?

### ISSUE THREAD

**Issue by simdnyan** [wilzbach/d-mans#3]
Currently, oiginal D-man SVG file is not hosted in anywhere is it?
https://forum.dlang.org/thread/qaatwevzygouqtnqkjbs@forum.dlang.org

Do we host that in this d-mans? Or where should we host?

file: https://web.archive.org/web/20050213192555/http://w148.de:80/~mmartin/d/dlogo.svg

**Comment by wilzbach** [comment]
Please find more than free to make a PR
