### ISSUE TITLE
Autogenerated listing doesn't work here

### ISSUE THREAD

**Issue by ghost** [wilzbach/d-mans#5]
https://dlang-community.github.io/d-mans

No listing displayed (FF quantum 64 bits 60.0.1).

**Comment by wilzbach** [comment]
You need to select a collection, e.g. https://dlang-community.github.io/d-mans/meiz/

**Comment by ghost** [comment]
ok. last time this was not necessary iirc.

**Comment by wilzbach** [comment]
Tried to make it a bit clearer with https://github.com/dlang-community/d-mans/pull/6
